global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using System.Net;
global using System.Text.Json.Serialization;
global using Microsoft.EntityFrameworkCore;
global using Product.Infrastructure;
global using Product.Application.Commands.ProductCommand;
global using Product.Infrastructure.Repositories;
global using Serilog;
global using MediatR;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Product.API.Filters;
global using System.Text;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Authorization;
global using Product.Application.Queries.ProductQuery;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.Extensions.Options;
global using Product.API.Middlewares;
//use ProductEntity to handle ambigous between reference and class model
global using ProductEntity = Product.Domain.AggregateModels.ProductAggregate.Product;